### ISSUE TITLE
I have forked recent example,but got some problem to run

### ISSUE THREAD

**Issue by Necmttn** [guncebektas/autocms#1]
i believe you're doing some test or upgrades that's why it's not working right now. anyway i having this crash

```
Meteor._wrapAsync has been renamed to Meteor.wrapAsync

/Users/necmettinkarakaya/.meteor/packages/meteor-tool/.1.1.10.1b51q9m++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
						throw(ex);
						      ^
Error: Meteor.userId can only be invoked in method calls. Use this.userId in publish functions.
    at AccountsServer.userId (accounts_server.js:80:13)
    at Object.Meteor.userId (accounts_common.js:222:19)
    at Object.settings.attachSchema.SimpleSchema.createdBy.autoValue (both/collections/settings.js:67:21)
    at Object.runAV (packages/aldeed_simple-schema/packages/aldeed_simple-schema.js:1181:1)
    at packages/aldeed_simple-schema/packages/aldeed_simple-schema.js:1282:1
    at Array.forEach (packages/es5-shim/.npm/package/node_modules/es5-shim/es5-shim.js:417:1)
    at Function._.each._.forEach (packages/underscore/underscore.js:105:1)
    at packages/aldeed_simple-schema/packages/aldeed_simple-schema.js:1281:1
    at Function._.each._.forEach (packages/underscore/underscore.js:113:1)
    at [object Object].getAutoValues (packages/aldeed_simple-schema/packages/aldeed_simple-schema.js:1244:1)
Exited with code: 8
Your application is crashing. Waiting for file change.
```
Saygılarımla

**Comment by guncebektas** [comment]
i see it, can u please share accounts_server.js and accounts_common.js The example was working on my last test. There could be a problem about Meteor.user object. I will create a new project and look it again tomorrow.

Saygılarla :)

**Comment by guncebektas** [comment]
i checked it now @Necmttn  Nothing is wrong in current example. If it's not hard for you can u please download it again and try. There might be a syntax or logic error in your code if you changed or added something. Waiting to here from u? Best regards.

**Comment by Necmttn** [comment]
i clone latest repo but still same, 
here's the crash repor 

```
Meteor._wrapAsync has been renamed to Meteor.wrapAsync

/Users/necmettinkarakaya/.meteor/packages/meteor-tool/.1.1.10.1b51q9m++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
						throw(ex);
						      ^
Error: Meteor.userId can only be invoked in method calls. Use this.userId in publish functions.
    at AccountsServer.userId (accounts_server.js:80:13)
    at Object.Meteor.userId (accounts_common.js:222:19)
    at Object.settings.attachSchema.SimpleSchema.createdBy.autoValue (both/collections/settings.js:67:21)
    at Object.runAV (packages/aldeed_simple-schema/packages/aldeed_simple-schema.js:1181:1)
    at packages/aldeed_simple-schema/packages/aldeed_simple-schema.js:1282:1
    at Array.forEach (packages/es5-shim/.npm/package/node_modules/es5-shim/es5-shim.js:417:1)
    at Function._.each._.forEach (packages/underscore/underscore.js:105:1)
    at packages/aldeed_simple-schema/packages/aldeed_simple-schema.js:1281:1
    at Function._.each._.forEach (packages/underscore/underscore.js:113:1)
    at [object Object].getAutoValues (packages/aldeed_simple-schema/packages/aldeed_simple-schema.js:1244:1)
Exited with code: 8
Your application is crashing. Waiting for file change.
```

**Comment by guncebektas** [comment]
Hi @Necmttn 
Sorry for the delay, i solved the problem and pushed the fix. Upgrading these two files will solve the problem.
- master/example/both/collections/settings.js
- master/example/cms/server/install/settings.js

Please inform me, best regards.

**Comment by Necmttn** [comment]
Up and Runing ! :+1:
